defaults:
  - lewm
  - override data: visual_scene
  - _self_

output_model_name: lewm_visual_scene
subdir: /data/ykz/scene/lewm_visual_scene

wandb:
  enabled: True
  config:
    entity: 3397765144-hust
    project: ogbench-visual-scene
    name: ${output_model_name}
    id: ${output_model_name}
    resume: allow
    log_model: False

wm:
  action_dim: 5
