name: pusht
data_root: /data/ykz/pusht
planner_dataset_path: /data/ykz/pusht/diffusion_pipeline/pusht_planner_dataset.pt
wm_policy: /data/ykz/pusht/lewm_epoch_100
output_dir: /data/ykz/pusht/diffusion_pipeline/pusht_corrector_ci${corrective.correction_interval}
